---
{{ if and .Values.destExternalSecret }}
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: {{ template "rclone.fullname" . }}-external-secret
  labels:
    {{- include "rclone.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: rclone-dest-sync-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        dest_provider_s3.creds: "{{ `{{ .creds_file }}` }}"
  data:
  - secretKey: creds_file
    remoteRef:
      key: {{ .Values.destExternalSecret }}
{{ end }}
---
